# Generated by Django 3.1.6 on 2021-03-15 01:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweetID', models.CharField(default=uuid.UUID('e0413af1-9e79-4f4a-818c-038094656bcc'), max_length=10, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('media', models.ImageField(upload_to='')),
                ('numLikes', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
