# Generated by Django 3.1.6 on 2021-03-15 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='numLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('5e9fed3e-9dff-4e84-a931-5a94817f99c5'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
