# Generated by Django 3.1.6 on 2021-03-15 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210315_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('80a29f3a-de3c-428a-89fb-20d16eaa6c62'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
