# Generated by Django 3.1.6 on 2021-03-15 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20210315_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('94000520-0d4a-4800-a27f-98606bc432f4'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
