# Generated by Django 3.1.6 on 2021-03-15 03:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20210315_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('cbad0543-a837-439f-8009-ddee8b959899'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
