# Generated by Django 3.1.6 on 2021-03-15 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20210315_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('94df20fa-8a1b-476d-9e5b-d1298a4e15fd'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
