# Generated by Django 3.1.6 on 2021-03-15 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20210315_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('56384893-9171-4fd4-ba40-48e97126a90b'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
