# Generated by Django 3.1.6 on 2021-03-15 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20210315_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('c5f6a09e-f900-4f97-9128-6a94b7484253'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
