# Generated by Django 3.1.6 on 2021-03-15 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20210315_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetID',
            field=models.CharField(default=uuid.UUID('fb0fca78-0e62-4aef-ac0f-cd95ecafc5b4'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
