# Generated by Django 3.1.6 on 2021-04-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_auto_20210317_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
