# Generated by Django 3.1.6 on 2021-04-07 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0014_auto_20210407_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
