# Generated by Django 3.1.6 on 2021-03-15 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210315_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('024895f1-1687-48e8-93e9-b0aaeac50bd2'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
