# Generated by Django 3.1.6 on 2021-03-15 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210315_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('784c55f3-e14f-4410-8c74-c8ec0f12369c'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
