# Generated by Django 3.1.6 on 2021-03-15 03:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210315_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('1356461c-1329-438f-803b-15601c576048'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
