# Generated by Django 3.1.6 on 2021-03-15 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210315_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('3ece6189-36c9-455f-a322-f2117639842c'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
