# Generated by Django 3.1.6 on 2021-03-15 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210315_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('6780bdff-8c49-4d85-9539-5609e81fe8be'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
