# Generated by Django 3.1.6 on 2021-03-15 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210315_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('b1c26600-eb51-4d0c-9db7-4acf5ec8d975'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
