# Generated by Django 3.1.6 on 2021-03-15 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210315_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('eb747953-40a6-4d53-9f19-83c9783e7a22'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
