# Generated by Django 3.1.6 on 2021-03-15 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210315_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='userID',
            field=models.CharField(default=uuid.UUID('e1c844dc-d23a-407e-bdd0-06c073dce892'), max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
