# Generated by Django 3.1.6 on 2021-04-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210317_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='media',
            field=models.ImageField(default='Default_Profile.jpeg', upload_to='profiles'),
        ),
    ]
