# Generated by Django 3.1.6 on 2021-04-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='media',
            new_name='profilePicture',
        ),
    ]
